//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yepa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yepa.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminum.
        /// </summary>
        public static string AIAluminum {
            get {
                return ResourceManager.GetString("AIAluminum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceramic and porcelain stoneware.
        /// </summary>
        public static string AICeramic {
            get {
                return ResourceManager.GetString("AICeramic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string AIComputers {
            get {
                return ResourceManager.GetString("AIComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drywall.
        /// </summary>
        public static string AIDrywall {
            get {
                return ResourceManager.GetString("AIDrywall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical.
        /// </summary>
        public static string AIElectrical {
            get {
                return ResourceManager.GetString("AIElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydraulics.
        /// </summary>
        public static string AIHydraulics {
            get {
                return ResourceManager.GetString("AIHydraulics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melamine.
        /// </summary>
        public static string AIMelamine {
            get {
                return ResourceManager.GetString("AIMelamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal constructions.
        /// </summary>
        public static string AIMetalconstructions {
            get {
                return ResourceManager.GetString("AIMetalconstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security cameras.
        /// </summary>
        public static string AISecuritycameras {
            get {
                return ResourceManager.GetString("AISecuritycameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding.
        /// </summary>
        public static string AIWelding {
            get {
                return ResourceManager.GetString("AIWelding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminum joinery.
        /// </summary>
        public static string Aluminumjoinery {
            get {
                return ResourceManager.GetString("Aluminumjoinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly and installation.
        /// </summary>
        public static string AssemblyInstallation {
            get {
                return ResourceManager.GetString("AssemblyInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already qualified.
        /// </summary>
        public static string CalificationError {
            get {
                return ResourceManager.GetString("CalificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cellrepairmaintenance {
            get {
                return ResourceManager.GetString("Cellrepairmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceramic and porcelain.
        /// </summary>
        public static string Ceramicporcelain {
            get {
                return ResourceManager.GetString("Ceramicporcelain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer assembly.
        /// </summary>
        public static string Computerassembly {
            get {
                return ResourceManager.GetString("Computerassembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computerrepairmaintenance {
            get {
                return ResourceManager.GetString("Computerrepairmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confection.
        /// </summary>
        public static string Confection {
            get {
                return ResourceManager.GetString("Confection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Account.
        /// </summary>
        public static string Confirmaccount {
            get {
                return ResourceManager.GetString("Confirmaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Createaccount {
            get {
                return ResourceManager.GetString("Createaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string Createnewaccount {
            get {
                return ResourceManager.GetString("Createnewaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string CSuits {
            get {
                return ResourceManager.GetString("CSuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniforms.
        /// </summary>
        public static string CUniforms {
            get {
                return ResourceManager.GetString("CUniforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is wrongly entered.
        /// </summary>
        public static string DataError {
            get {
                return ResourceManager.GetString("DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic electrical installation.
        /// </summary>
        public static string Domesticelectricalinstallation {
            get {
                return ResourceManager.GetString("Domesticelectricalinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic hydraulic installation.
        /// </summary>
        public static string Domestichydraulicinstallation {
            get {
                return ResourceManager.GetString("Domestichydraulicinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drywall Construction.
        /// </summary>
        public static string DrywallConstruction {
            get {
                return ResourceManager.GetString("DrywallConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string Editprofile {
            get {
                return ResourceManager.GetString("Editprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is not verified, do you want to resend the verification link?.
        /// </summary>
        public static string Emailnotactive {
            get {
                return ResourceManager.GetString("Emailnotactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string Entercode {
            get {
                return ResourceManager.GetString("Entercode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code we sent.
        /// </summary>
        public static string Entercodesent {
            get {
                return ResourceManager.GetString("Entercodesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        public static string Enternewpassword {
            get {
                return ResourceManager.GetString("Enternewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Your Account.
        /// </summary>
        public static string Findaccount {
            get {
                return ResourceManager.GetString("Findaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your first name.
        /// </summary>
        public static string FirstnameError {
            get {
                return ResourceManager.GetString("FirstnameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Forgotpassword {
            get {
                return ResourceManager.GetString("Forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight transport.
        /// </summary>
        public static string Freighttransport {
            get {
                return ResourceManager.GetString("Freighttransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geting location....
        /// </summary>
        public static string GetLocation {
            get {
                return ResourceManager.GetString("GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting the location.
        /// </summary>
        public static string GetLocationError {
            get {
                return ResourceManager.GetString("GetLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You agree to give your location?.
        /// </summary>
        public static string Givelocation {
            get {
                return ResourceManager.GetString("Givelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an acount?.
        /// </summary>
        public static string Haveacount {
            get {
                return ResourceManager.GetString("Haveacount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid useremail or password.
        /// </summary>
        public static string Invalidlogin {
            get {
                return ResourceManager.GetString("Invalidlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your last name.
        /// </summary>
        public static string LastnameError {
            get {
                return ResourceManager.GetString("LastnameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to know your location.
        /// </summary>
        public static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniforms.
        /// </summary>
        public static string Makinguniforms {
            get {
                return ResourceManager.GetString("Makinguniforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melamine Furniture.
        /// </summary>
        public static string MelamineFurniture {
            get {
                return ResourceManager.GetString("MelamineFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal constructions.
        /// </summary>
        public static string Metalconstructions {
            get {
                return ResourceManager.GetString("Metalconstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name and last name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Newpassword {
            get {
                return ResourceManager.GetString("Newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal transportation (taxi).
        /// </summary>
        public static string Personaltransportation {
            get {
                return ResourceManager.GetString("Personaltransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printerrepairmaintenance {
            get {
                return ResourceManager.GetString("Printerrepairmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualify.
        /// </summary>
        public static string Qualify {
            get {
                return ResourceManager.GetString("Qualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string Registernow {
            get {
                return ResourceManager.GetString("Registernow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair and Maintenance.
        /// </summary>
        public static string RepairMaintenance {
            get {
                return ResourceManager.GetString("RepairMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household appliances.
        /// </summary>
        public static string Repairmaintenancehouseholdappliances {
            get {
                return ResourceManager.GetString("Repairmaintenancehouseholdappliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phones.
        /// </summary>
        public static string RPCellphones {
            get {
                return ResourceManager.GetString("RPCellphones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string RPComputers {
            get {
                return ResourceManager.GetString("RPComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home appliances.
        /// </summary>
        public static string RPHomeappliances {
            get {
                return ResourceManager.GetString("RPHomeappliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        public static string RPPrinters {
            get {
                return ResourceManager.GetString("RPPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security cameras.
        /// </summary>
        public static string Securitycameras {
            get {
                return ResourceManager.GetString("Securitycameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        public static string Signincontinue {
            get {
                return ResourceManager.GetString("Signincontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with a verification link has been sent to your email, press it to log in.
        /// </summary>
        public static string SingupVerification {
            get {
                return ResourceManager.GetString("SingupVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string Suits {
            get {
                return ResourceManager.GetString("Suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight transportation.
        /// </summary>
        public static string TFreighttransportation {
            get {
                return ResourceManager.GetString("TFreighttransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal transportation.
        /// </summary>
        public static string TPersonalTransportation {
            get {
                return ResourceManager.GetString("TPersonalTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a username.
        /// </summary>
        public static string UsernameError {
            get {
                return ResourceManager.GetString("UsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string Welcomeback {
            get {
                return ResourceManager.GetString("Welcomeback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding.
        /// </summary>
        public static string Welding {
            get {
                return ResourceManager.GetString("Welding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your app.
        /// </summary>
        public static string Yourapp {
            get {
                return ResourceManager.GetString("Yourapp", resourceCulture);
            }
        }
    }
}
