//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yepa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceCategory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCategory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yepa.Resources.ResourceCategory", typeof(ResourceCategory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceramic and porcelain stoneware.
        /// </summary>
        public static string AICeramic {
            get {
                return ResourceManager.GetString("AICeramic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string AIComputers {
            get {
                return ResourceManager.GetString("AIComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drywall.
        /// </summary>
        public static string AIDrywall {
            get {
                return ResourceManager.GetString("AIDrywall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical.
        /// </summary>
        public static string AIElectrical {
            get {
                return ResourceManager.GetString("AIElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydraulics.
        /// </summary>
        public static string AIHydraulics {
            get {
                return ResourceManager.GetString("AIHydraulics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melamine.
        /// </summary>
        public static string AIMelamine {
            get {
                return ResourceManager.GetString("AIMelamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal constructions.
        /// </summary>
        public static string AIMetalconstructions {
            get {
                return ResourceManager.GetString("AIMetalconstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security cameras.
        /// </summary>
        public static string AISecuritycameras {
            get {
                return ResourceManager.GetString("AISecuritycameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding.
        /// </summary>
        public static string AIWelding {
            get {
                return ResourceManager.GetString("AIWelding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminum joinery.
        /// </summary>
        public static string Aluminumjoinery {
            get {
                return ResourceManager.GetString("Aluminumjoinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly and installation.
        /// </summary>
        public static string AssemblyInstallation {
            get {
                return ResourceManager.GetString("AssemblyInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cellrepairmaintenance {
            get {
                return ResourceManager.GetString("Cellrepairmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceramic and porcelain.
        /// </summary>
        public static string Ceramicporcelain {
            get {
                return ResourceManager.GetString("Ceramicporcelain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer assembly.
        /// </summary>
        public static string Computerassembly {
            get {
                return ResourceManager.GetString("Computerassembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computerrepairmaintenance {
            get {
                return ResourceManager.GetString("Computerrepairmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confection.
        /// </summary>
        public static string Confection {
            get {
                return ResourceManager.GetString("Confection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string CSuits {
            get {
                return ResourceManager.GetString("CSuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniforms.
        /// </summary>
        public static string CUniforms {
            get {
                return ResourceManager.GetString("CUniforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic electrical installation.
        /// </summary>
        public static string Domesticelectricalinstallation {
            get {
                return ResourceManager.GetString("Domesticelectricalinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic hydraulic installation.
        /// </summary>
        public static string Domestichydraulicinstallation {
            get {
                return ResourceManager.GetString("Domestichydraulicinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drywall Construction.
        /// </summary>
        public static string DrywallConstruction {
            get {
                return ResourceManager.GetString("DrywallConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight transport.
        /// </summary>
        public static string Freighttransport {
            get {
                return ResourceManager.GetString("Freighttransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniforms.
        /// </summary>
        public static string Makinguniforms {
            get {
                return ResourceManager.GetString("Makinguniforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melamine Furniture.
        /// </summary>
        public static string MelamineFurniture {
            get {
                return ResourceManager.GetString("MelamineFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal constructions.
        /// </summary>
        public static string Metalconstructions {
            get {
                return ResourceManager.GetString("Metalconstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal transportation (taxi).
        /// </summary>
        public static string Personaltransportation {
            get {
                return ResourceManager.GetString("Personaltransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printerrepairmaintenance {
            get {
                return ResourceManager.GetString("Printerrepairmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair and Maintenance.
        /// </summary>
        public static string RepairMaintenance {
            get {
                return ResourceManager.GetString("RepairMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household appliances.
        /// </summary>
        public static string Repairmaintenancehouseholdappliances {
            get {
                return ResourceManager.GetString("Repairmaintenancehouseholdappliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phones.
        /// </summary>
        public static string RPCellphones {
            get {
                return ResourceManager.GetString("RPCellphones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string RPComputers {
            get {
                return ResourceManager.GetString("RPComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home appliances.
        /// </summary>
        public static string RPHomeappliances {
            get {
                return ResourceManager.GetString("RPHomeappliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        public static string RPPrinters {
            get {
                return ResourceManager.GetString("RPPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security cameras.
        /// </summary>
        public static string Securitycameras {
            get {
                return ResourceManager.GetString("Securitycameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string Suits {
            get {
                return ResourceManager.GetString("Suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight transportation.
        /// </summary>
        public static string TFreighttransportation {
            get {
                return ResourceManager.GetString("TFreighttransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal transportation.
        /// </summary>
        public static string TPersonalTransportation {
            get {
                return ResourceManager.GetString("TPersonalTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding.
        /// </summary>
        public static string Welding {
            get {
                return ResourceManager.GetString("Welding", resourceCulture);
            }
        }
    }
}
